"""Violation view constants (no dedicated DB table — aggregated from existing sources)."""

from __future__ import annotations

VIOLATION_STATUS_OPEN = "OPEN"
VIOLATION_STATUS_QUARANTINED = "QUARANTINED"
VIOLATION_STATUS_RELEASED = "RELEASED"
VIOLATION_STATUS_REPLAYED = "REPLAYED"

VIOLATION_STATUSES = frozenset(
    {
        VIOLATION_STATUS_OPEN,
        VIOLATION_STATUS_QUARANTINED,
        VIOLATION_STATUS_RELEASED,
        VIOLATION_STATUS_REPLAYED,
    }
)

VIOLATION_SEVERITY_HIGH = "HIGH"
VIOLATION_SEVERITY_MEDIUM = "MEDIUM"
VIOLATION_SEVERITY_LOW = "LOW"

VIOLATION_SEVERITIES = frozenset(
    {
        VIOLATION_SEVERITY_HIGH,
        VIOLATION_SEVERITY_MEDIUM,
        VIOLATION_SEVERITY_LOW,
    }
)

VIOLATION_WINDOW_24H = "24h"
VIOLATION_WINDOW_7D = "7d"
VIOLATION_WINDOW_30D = "30d"

VIOLATION_WINDOWS = frozenset({VIOLATION_WINDOW_24H, VIOLATION_WINDOW_7D, VIOLATION_WINDOW_30D})

VIOLATION_SOURCE_QUARANTINE = "quarantine"
