"""Quarantine operations view constants (no dedicated DB table)."""

from __future__ import annotations

QUARANTINE_DISPLAY_QUARANTINED = "QUARANTINED"
QUARANTINE_DISPLAY_RELEASED = "RELEASED"
QUARANTINE_DISPLAY_DISCARDED = "DISCARDED"
QUARANTINE_DISPLAY_REPLAYED = "REPLAYED"

QUARANTINE_DISPLAY_STATUSES = frozenset(
    {
        QUARANTINE_DISPLAY_QUARANTINED,
        QUARANTINE_DISPLAY_RELEASED,
        QUARANTINE_DISPLAY_DISCARDED,
        QUARANTINE_DISPLAY_REPLAYED,
    }
)

QUARANTINE_WINDOW_24H = "24h"
QUARANTINE_WINDOW_7D = "7d"
QUARANTINE_WINDOW_30D = "30d"

QUARANTINE_WINDOWS = frozenset({QUARANTINE_WINDOW_24H, QUARANTINE_WINDOW_7D, QUARANTINE_WINDOW_30D})
