"""Governance audit trail constants (M19.3)."""

from __future__ import annotations

AUDIT_EVENT_POLICY_ACTIVATED = "POLICY_ACTIVATED"
AUDIT_EVENT_POLICY_SUBMITTED = "SUBMITTED_FOR_REVIEW"
AUDIT_EVENT_POLICY_APPROVED = "APPROVED"
AUDIT_EVENT_POLICY_REJECTED = "REJECTED"
AUDIT_EVENT_POLICY_REQUEST_CHANGES = "REQUEST_CHANGES"
AUDIT_EVENT_POLICY_APPROVAL_ACTIVATED = "APPROVAL_ACTIVATED"
AUDIT_EVENT_VIOLATION_CREATED = "VIOLATION_CREATED"
AUDIT_EVENT_QUARANTINE_CREATED = "QUARANTINE_CREATED"
AUDIT_EVENT_QUARANTINE_RELEASED = "QUARANTINE_RELEASED"
AUDIT_EVENT_QUARANTINE_DISCARDED = "QUARANTINE_DISCARDED"
AUDIT_EVENT_REPLAY_STARTED = "REPLAY_STARTED"
AUDIT_EVENT_REPLAY_COMPLETED = "REPLAY_COMPLETED"
AUDIT_EVENT_REPLAY_FAILED = "REPLAY_FAILED"

AUDIT_EVENT_TYPES = frozenset(
    {
        AUDIT_EVENT_POLICY_ACTIVATED,
        AUDIT_EVENT_POLICY_SUBMITTED,
        AUDIT_EVENT_POLICY_APPROVED,
        AUDIT_EVENT_POLICY_REJECTED,
        AUDIT_EVENT_POLICY_REQUEST_CHANGES,
        AUDIT_EVENT_POLICY_APPROVAL_ACTIVATED,
        AUDIT_EVENT_VIOLATION_CREATED,
        AUDIT_EVENT_QUARANTINE_CREATED,
        AUDIT_EVENT_QUARANTINE_RELEASED,
        AUDIT_EVENT_QUARANTINE_DISCARDED,
        AUDIT_EVENT_REPLAY_STARTED,
        AUDIT_EVENT_REPLAY_COMPLETED,
        AUDIT_EVENT_REPLAY_FAILED,
    }
)

AUDIT_STATUS_ACTIVE = "ACTIVE"
AUDIT_STATUS_OPEN = "OPEN"
AUDIT_STATUS_QUARANTINED = "QUARANTINED"
AUDIT_STATUS_RELEASED = "RELEASED"
AUDIT_STATUS_DISCARDED = "DISCARDED"
AUDIT_STATUS_IN_PROGRESS = "IN_PROGRESS"
AUDIT_STATUS_DELIVERED = "DELIVERED"
AUDIT_STATUS_FAILED = "FAILED"

AUDIT_STATUSES = frozenset(
    {
        AUDIT_STATUS_ACTIVE,
        AUDIT_STATUS_OPEN,
        AUDIT_STATUS_QUARANTINED,
        AUDIT_STATUS_RELEASED,
        AUDIT_STATUS_DISCARDED,
        AUDIT_STATUS_IN_PROGRESS,
        AUDIT_STATUS_DELIVERED,
        AUDIT_STATUS_FAILED,
    }
)

AUDIT_OUTCOME_DELIVERED = "DELIVERED"
AUDIT_OUTCOME_DISCARDED = "DISCARDED"
AUDIT_OUTCOME_FAILED = "FAILED"

AUDIT_OUTCOMES = frozenset({AUDIT_OUTCOME_DELIVERED, AUDIT_OUTCOME_DISCARDED, AUDIT_OUTCOME_FAILED})

AUDIT_WINDOW_24H = "24h"
AUDIT_WINDOW_7D = "7d"
AUDIT_WINDOW_30D = "30d"

AUDIT_WINDOWS = frozenset({AUDIT_WINDOW_24H, AUDIT_WINDOW_7D, AUDIT_WINDOW_30D})
