/** Static demo data for the Routes operational overview (no backend). */

export type RouteOperationalStatus = 'ENABLED' | 'DEGRADED' | 'ERROR' | 'DISABLED'

export type MockRouteRow = {
  id: string
  /** e.g. Malop API → Stellar SIEM */
  routeLabel: string
  streamName: string
  connectorName: string
  /** e.g. Stellar SIEM (Syslog UDP) */
  destinationLabel: string
  destinationKind: 'SYSLOG_UDP' | 'SYSLOG_TCP' | 'WEBHOOK_POST'
  status: RouteOperationalStatus
  deliveryPct1h: number
  eventsPerMin: number
  failed1h: number
  latencyP95Ms: number
  latencySparkline: readonly number[]
  failurePolicyTitle: string
  failurePolicyDetail: string
  /** null when no recent error */
  lastError: string | null
}

export const ROUTES_KPI = {
  total: 24,
  totalTrend: '↑ 2 from last 7 days',
  enabled: 20,
  enabledPct: '83.3%',
  deliverySuccess1h: 99.25,
  deliveryTrend: '↑ 1.21% vs yesterday',
  failedEvents1h: 186,
  failedTrend: '↓ 23 vs yesterday',
  avgLatencyP95Ms: 24,
  latencyTrend: '↓ 8 ms vs yesterday',
  destinationsTotal: 8,
  destinationsHealthy: 5,
  destinationsIssues: 3,
} as const

export const CONNECTOR_FILTER_OPTIONS = [
  'All Connectors',
  'Cybereason',
  'CrowdStrike',
  'Custom API',
  'Palo Alto',
] as const

export const STREAM_FILTER_OPTIONS = [
  'All Streams',
  'Malop API',
  'Hunting API',
  'Sensor API',
  'Detections',
  'Audit Log',
  'Custom Stream',
] as const

export const DESTINATION_FILTER_OPTIONS = [
  'All Destinations',
  'Stellar SIEM',
  'Backup Syslog',
  'SIEM Webhook',
  'Splunk HEC',
  'Elastic Webhook',
] as const

export const STATUS_FILTER_OPTIONS = ['All Statuses', 'ENABLED', 'DEGRADED', 'ERROR', 'DISABLED'] as const

export const MOCK_ROUTE_ROWS: MockRouteRow[] = [
  {
    id: 'rt-malop-stellar-udp',
    routeLabel: 'Malop API → Stellar SIEM (UDP)',
    streamName: 'Malop API',
    connectorName: 'Cybereason',
    destinationLabel: 'Stellar SIEM (Syslog UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ENABLED',
    deliveryPct1h: 99.7,
    eventsPerMin: 2072,
    failed1h: 61,
    latencyP95Ms: 18,
    latencySparkline: [22, 20, 19, 18, 17, 18, 18],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Max 10 retries',
    lastError: '2m ago · HTTP 500',
  },
  {
    id: 'rt-malop-webhook',
    routeLabel: 'Malop API → SIEM Webhook',
    streamName: 'Malop API',
    connectorName: 'Cybereason',
    destinationLabel: 'SIEM Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'DEGRADED',
    deliveryPct1h: 94.2,
    eventsPerMin: 412,
    failed1h: 28,
    latencyP95Ms: 142,
    latencySparkline: [120, 128, 135, 140, 138, 142, 141],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Exponential · cap 120s',
    lastError: '1m ago · Connection refused',
  },
  {
    id: 'rt-hunting-stellar',
    routeLabel: 'Hunting API → Stellar SIEM (TCP)',
    streamName: 'Hunting API',
    connectorName: 'Cybereason',
    destinationLabel: 'Stellar SIEM (Syslog TCP)',
    destinationKind: 'SYSLOG_TCP',
    status: 'ENABLED',
    deliveryPct1h: 99.91,
    eventsPerMin: 118,
    failed1h: 2,
    latencyP95Ms: 34,
    latencySparkline: [36, 35, 34, 33, 34, 34, 34],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'Pause stream off',
    lastError: null,
  },
  {
    id: 'rt-sensor-backup',
    routeLabel: 'Sensor API → Backup Syslog',
    streamName: 'Sensor API',
    connectorName: 'Cybereason',
    destinationLabel: 'Backup Syslog (UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ERROR',
    deliveryPct1h: 72.4,
    eventsPerMin: 890,
    failed1h: 312,
    latencyP95Ms: 210,
    latencySparkline: [180, 195, 205, 212, 208, 210, 211],
    failurePolicyTitle: 'Pause stream',
    failurePolicyDetail: 'On repeated failure',
    lastError: '30s ago · TLS handshake failed',
  },
  {
    id: 'rt-cs-detect-splunk',
    routeLabel: 'Detections → Splunk HEC',
    streamName: 'Detections',
    connectorName: 'CrowdStrike',
    destinationLabel: 'Splunk HEC (HTTPS)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.25,
    eventsPerMin: 3401,
    failed1h: 12,
    latencyP95Ms: 56,
    latencySparkline: [62, 58, 57, 56, 55, 56, 56],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Max 6 retries',
    lastError: '4m ago · HTTP 429',
  },
  {
    id: 'rt-cs-detect-elastic',
    routeLabel: 'Detections → Elastic Webhook',
    streamName: 'Detections',
    connectorName: 'CrowdStrike',
    destinationLabel: 'Elastic Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'DEGRADED',
    deliveryPct1h: 91.0,
    eventsPerMin: 1205,
    failed1h: 104,
    latencyP95Ms: 88,
    latencySparkline: [76, 80, 85, 88, 87, 88, 89],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'DLQ to logs',
    lastError: '12m ago · Read timed out',
  },
  {
    id: 'rt-audit-stellar',
    routeLabel: 'Audit Log → Stellar SIEM (UDP)',
    streamName: 'Audit Log',
    connectorName: 'Palo Alto',
    destinationLabel: 'Stellar SIEM (Syslog UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ENABLED',
    deliveryPct1h: 100,
    eventsPerMin: 44,
    failed1h: 0,
    latencyP95Ms: 12,
    latencySparkline: [14, 13, 12, 12, 12, 12, 12],
    failurePolicyTitle: 'Disable route',
    failurePolicyDetail: 'After 5 hard fails',
    lastError: null,
  },
  {
    id: 'rt-custom-siem',
    routeLabel: 'Custom feed → SIEM Webhook',
    streamName: 'Custom Stream',
    connectorName: 'Custom API',
    destinationLabel: 'SIEM Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'DISABLED',
    deliveryPct1h: 0,
    eventsPerMin: 0,
    failed1h: 0,
    latencyP95Ms: 0,
    latencySparkline: [0, 0, 0, 0, 0, 0, 0],
    failurePolicyTitle: 'Disable route',
    failurePolicyDetail: 'Operator paused',
    lastError: '—',
  },
  {
    id: 'rt-malop-backup',
    routeLabel: 'Malop API → Backup Syslog',
    streamName: 'Malop API',
    connectorName: 'Cybereason',
    destinationLabel: 'Backup Syslog (UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ENABLED',
    deliveryPct1h: 98.8,
    eventsPerMin: 1988,
    failed1h: 24,
    latencyP95Ms: 21,
    latencySparkline: [24, 23, 22, 21, 21, 21, 21],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Max 10 retries',
    lastError: '6m ago · transient 503',
  },
  {
    id: 'rt-hunting-webhook',
    routeLabel: 'Hunting API → SIEM Webhook',
    streamName: 'Hunting API',
    connectorName: 'Cybereason',
    destinationLabel: 'SIEM Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.4,
    eventsPerMin: 95,
    failed1h: 1,
    latencyP95Ms: 48,
    latencySparkline: [52, 50, 49, 48, 48, 48, 47],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'Non-blocking',
    lastError: null,
  },
  {
    id: 'rt-sensor-splunk',
    routeLabel: 'Sensor API → Splunk HEC',
    streamName: 'Sensor API',
    connectorName: 'Cybereason',
    destinationLabel: 'Splunk HEC (HTTPS)',
    destinationKind: 'WEBHOOK_POST',
    status: 'DEGRADED',
    deliveryPct1h: 96.1,
    eventsPerMin: 640,
    failed1h: 41,
    latencyP95Ms: 112,
    latencySparkline: [98, 104, 108, 110, 112, 111, 112],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Jitter · cap 90s',
    lastError: '3m ago · rate limited',
  },
  {
    id: 'rt-detect-stellar2',
    routeLabel: 'Detections → Stellar SIEM (TCP)',
    streamName: 'Detections',
    connectorName: 'CrowdStrike',
    destinationLabel: 'Stellar SIEM (Syslog TCP)',
    destinationKind: 'SYSLOG_TCP',
    status: 'ENABLED',
    deliveryPct1h: 99.88,
    eventsPerMin: 3302,
    failed1h: 4,
    latencyP95Ms: 41,
    latencySparkline: [45, 43, 42, 41, 41, 41, 41],
    failurePolicyTitle: 'Pause stream',
    failurePolicyDetail: 'Webhook primary down',
    lastError: null,
  },
  {
    id: 'rt-audit-backup',
    routeLabel: 'Audit Log → Backup Syslog',
    streamName: 'Audit Log',
    connectorName: 'Palo Alto',
    destinationLabel: 'Backup Syslog (UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ENABLED',
    deliveryPct1h: 99.2,
    eventsPerMin: 40,
    failed1h: 1,
    latencyP95Ms: 15,
    latencySparkline: [18, 17, 16, 15, 15, 15, 15],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'Secondary path',
    lastError: '45m ago · port unreachable',
  },
  {
    id: 'rt-custom-elastic',
    routeLabel: 'Custom feed → Elastic Webhook',
    streamName: 'Custom Stream',
    connectorName: 'Custom API',
    destinationLabel: 'Elastic Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ERROR',
    deliveryPct1h: 68.0,
    eventsPerMin: 512,
    failed1h: 164,
    latencyP95Ms: 260,
    latencySparkline: [220, 235, 250, 258, 260, 259, 260],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Max 8 retries',
    lastError: '1m ago · DNS failure',
  },
  {
    id: 'rt-malop-elastic',
    routeLabel: 'Malop API → Elastic Webhook',
    streamName: 'Malop API',
    connectorName: 'Cybereason',
    destinationLabel: 'Elastic Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.5,
    eventsPerMin: 1890,
    failed1h: 9,
    latencyP95Ms: 62,
    latencySparkline: [68, 65, 63, 62, 62, 62, 61],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'Overflow to backup',
    lastError: '18m ago · HTTP 502',
  },
  {
    id: 'rt-hunting-backup',
    routeLabel: 'Hunting API → Backup Syslog',
    streamName: 'Hunting API',
    connectorName: 'Cybereason',
    destinationLabel: 'Backup Syslog (UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ENABLED',
    deliveryPct1h: 99.0,
    eventsPerMin: 92,
    failed1h: 3,
    latencyP95Ms: 27,
    latencySparkline: [30, 29, 28, 27, 27, 27, 27],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Max 5 retries',
    lastError: null,
  },
  {
    id: 'rt-sensor-siem',
    routeLabel: 'Sensor API → SIEM Webhook',
    streamName: 'Sensor API',
    connectorName: 'Cybereason',
    destinationLabel: 'SIEM Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'DEGRADED',
    deliveryPct1h: 93.0,
    eventsPerMin: 820,
    failed1h: 58,
    latencyP95Ms: 155,
    latencySparkline: [140, 146, 150, 153, 155, 154, 155],
    failurePolicyTitle: 'Pause stream',
    failurePolicyDetail: 'After policy breach',
    lastError: '2m ago · HTTP 500',
  },
  {
    id: 'rt-detect-backup',
    routeLabel: 'Detections → Backup Syslog',
    streamName: 'Detections',
    connectorName: 'CrowdStrike',
    destinationLabel: 'Backup Syslog (UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ENABLED',
    deliveryPct1h: 99.7,
    eventsPerMin: 3290,
    failed1h: 11,
    latencyP95Ms: 38,
    latencySparkline: [42, 40, 39, 38, 38, 38, 38],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'Audit retained',
    lastError: null,
  },
  {
    id: 'rt-audit-siem',
    routeLabel: 'Audit Log → SIEM Webhook',
    streamName: 'Audit Log',
    connectorName: 'Palo Alto',
    destinationLabel: 'SIEM Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.9,
    eventsPerMin: 43,
    failed1h: 0,
    latencyP95Ms: 19,
    latencySparkline: [22, 21, 20, 19, 19, 19, 19],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Max 4 retries',
    lastError: null,
  },
  {
    id: 'rt-custom-stellar',
    routeLabel: 'Custom feed → Stellar SIEM (UDP)',
    streamName: 'Custom Stream',
    connectorName: 'Custom API',
    destinationLabel: 'Stellar SIEM (Syslog UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'DISABLED',
    deliveryPct1h: 0,
    eventsPerMin: 0,
    failed1h: 0,
    latencyP95Ms: 0,
    latencySparkline: [5, 4, 2, 1, 0, 0, 0],
    failurePolicyTitle: 'Disable route',
    failurePolicyDetail: 'Maintenance window',
    lastError: '—',
  },
  {
    id: 'rt-malop-splunk',
    routeLabel: 'Malop API → Splunk HEC',
    streamName: 'Malop API',
    connectorName: 'Cybereason',
    destinationLabel: 'Splunk HEC (HTTPS)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.62,
    eventsPerMin: 2010,
    failed1h: 7,
    latencyP95Ms: 51,
    latencySparkline: [56, 54, 52, 51, 51, 51, 50],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Token rotate aware',
    lastError: '9m ago · token expired (recovered)',
  },
  {
    id: 'rt-hunting-elastic',
    routeLabel: 'Hunting API → Elastic Webhook',
    streamName: 'Hunting API',
    connectorName: 'Cybereason',
    destinationLabel: 'Elastic Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.3,
    eventsPerMin: 96,
    failed1h: 2,
    latencyP95Ms: 44,
    latencySparkline: [48, 46, 45, 44, 44, 44, 44],
    failurePolicyTitle: 'Log and continue',
    failurePolicyDetail: 'Low volume',
    lastError: null,
  },
  {
    id: 'rt-sensor-stellar',
    routeLabel: 'Sensor API → Stellar SIEM (UDP)',
    streamName: 'Sensor API',
    connectorName: 'Cybereason',
    destinationLabel: 'Stellar SIEM (Syslog UDP)',
    destinationKind: 'SYSLOG_UDP',
    status: 'ERROR',
    deliveryPct1h: 61.2,
    eventsPerMin: 720,
    failed1h: 402,
    latencyP95Ms: 320,
    latencySparkline: [280, 295, 310, 318, 320, 319, 320],
    failurePolicyTitle: 'Pause stream',
    failurePolicyDetail: 'Escalate on loss',
    lastError: '45s ago · Connection reset',
  },
  {
    id: 'rt-detect-siem',
    routeLabel: 'Detections → SIEM Webhook',
    streamName: 'Detections',
    connectorName: 'CrowdStrike',
    destinationLabel: 'SIEM Webhook (POST)',
    destinationKind: 'WEBHOOK_POST',
    status: 'ENABLED',
    deliveryPct1h: 99.81,
    eventsPerMin: 3320,
    failed1h: 6,
    latencyP95Ms: 47,
    latencySparkline: [52, 49, 48, 47, 47, 47, 47],
    failurePolicyTitle: 'Retry with backoff',
    failurePolicyDetail: 'Dual endpoint',
    lastError: null,
  },
]
