"""Display constants for governance replay operations (M20.1)."""

from __future__ import annotations

REPLAY_DISPLAY_PENDING = "PENDING"
REPLAY_DISPLAY_RUNNING = "RUNNING"
REPLAY_DISPLAY_COMPLETED = "COMPLETED"
REPLAY_DISPLAY_FAILED = "FAILED"
REPLAY_DISPLAY_DISCARDED = "DISCARDED"

REPLAY_DISPLAY_STATUSES = frozenset(
    {
        REPLAY_DISPLAY_PENDING,
        REPLAY_DISPLAY_RUNNING,
        REPLAY_DISPLAY_COMPLETED,
        REPLAY_DISPLAY_FAILED,
        REPLAY_DISPLAY_DISCARDED,
    }
)

REPLAY_WINDOW_24H = "24h"
REPLAY_WINDOW_7D = "7d"
REPLAY_WINDOW_30D = "30d"

REPLAY_WINDOWS = frozenset({REPLAY_WINDOW_24H, REPLAY_WINDOW_7D, REPLAY_WINDOW_30D})

REPLAY_OUTCOME_SUCCESS = "Success"
REPLAY_OUTCOME_FAILURE = "Failure"
REPLAY_OUTCOME_DISCARDED = "Discarded"

REPLAY_ORIGIN_DELIVERY_FAILURE = "Delivery failure recovery"
REPLAY_ORIGIN_QUARANTINE = "Quarantine recovery"
